### ISSUE TITLE
The RAML file name still contains "fuse-" prefix

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/core-command#27]
The RAML file name still contains "fuse-" prefix, and it should be removed
Please see
https://github.com/edgexfoundry/core-command/tree/master/src/test/resources/raml

**Comment by jpwhitemn** [comment]
official raml for service @ https://github.com/edgexfoundry/edgex-go/blob/master/core/command/raml/core-command.raml does not contain fuse.
